Update load-tests
change artillery version from latest 1.6.0-27 to 1.6.0-15 for troubleshooting on the bellow:
npm info ok 
Running artillery load tests...
/usr/local/lib/node_modules/artillery/node_modules/csv-parse/lib/index.js:19
    super({...{readableObjectMode: true}, ...opts})
           ^^^
SyntaxError: Unexpected token ...
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/artillery/lib/commands/run.js:12:13)
    at Module._compile (module.js:556:32)